#!/bin/bash

# script directory
srcdir=$HOME/analysis/HDFcompress

# study name and directory
export STUDY=HDFcompress
export STUDYDIR=$WORK/HDFcompress

# add fat and bender directories to path
export PATH=$PATH:$srcdir
export PYTHONPATH=$PYTHONPATH:$srcdir
export SRCDIR=$srcdir
