#!/bin/bash
# TACC profile for working on HDFcompress project

# script directory
srcdir=$HOME/analysis/HDFcompress

# study name and directory for the data used to develop these scripts
export STUDY=HDFcompress
export STUDYDIR=$WORK/HDFcompress

# add script directory to search paths
export PATH=$PATH:$srcdir
export PYTHONPATH=$PYTHONPATH:$srcdir:$srcdir/config_files
export SRCDIR=$srcdir
